site_name: Ping Identity DevOps
repo_name: pingidentity/pingidentity-devops-getting-started
repo_url: https://github.com/pingidentity/pingidentity-devops-getting-started
site_url: https://devops.pingidentity.com/
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
   # scheme: preference
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

nav:
  - DEVOPS @ PING: "README.md"
  - OVERVIEW: "overview.md"
  - GET STARTED:
      - Introduction: "getStarted.md"
      - DevOps registration: "devopsRegistration.md"
      - Deploy an example stack: "getStartedWithGitRepo.md"
      - DevOps product licenses: "PROD-LICENSE.md"
      - Using your DevOps user and key: "devopsUserKey.md"
      - Using an existing product license: "existingLicense.md"
      - Saving your configuration changes: "saveConfigs.md"
  - WORKING WITH IMAGES:
      - Introduction: "deploy.md"
      - Build a Docker product image locally: "buildLocal.md"
      - Deploy standalone containers: "deployStandalone.md"
      - Orchestrate with Docker-Compose:
          - Introduction: "deployCompose.md"
          - Deploy a PingFederate and PingDirectory stack: "deploySimpleStack.md"
          - Deploy a replicated PingDirectory pair: "deployReplication.md"
          - Deploy PingDirectory with data synchronization using PingDataSync: "deploySync.md"
          - Deploy PingCentral: "deployPingCentral.md"
          - Deploy a PingFederate cluster: "deployPfCluster.md"
          - Deploy a PingAccess cluster: "deployPaCluster.md"
          - Deploy PingDataGovernance with PAP: "deployPdgPap.md"
          - Deploy a monitoring stack: "deployMonitoringStack.md"
          - Deploy an Elasticsearch SIEM stack: "deploySiemStack.md"
      - Orchestrate with Kubernetes:
          - Introduction: "deployK8s.md"
          - Deploy with PingIdentiy Helm Charts: "deployHelm.md"
          - PingDirectory deployments across Kubernetes clusters: "deployK8sPD-clusters.md"
          - Kubernetes deployments for general use:
              - Introduction: "deployK8sGeneral.md"
              - Orchestrate standalone deployments: "deployK8sStandalone.md"
              - Orchestrate a full stack deployment: "deployK8sFullstack.md"
              - Orchestrate a replicated PingDirectory deployment: "deployK8sReplicated.md"
              - Orchestrate a PingAccess cluster deployment: "deployK8sPA-cluster.md"
              - Orchestrate a PingFederate cluster deployment: "deployK8sPF-cluster.md"
              - Deploy PingFederate Across Multiple Kubernetes Clusters:
                  - Introduction: "deployK8sPFclusters.md"
                  - PingFederate Across Kubernetes with DNS: "deployPFMultiRegionDNS.md"
                  - PingFederate Across Kubernetes with S3: "deployPFMultiRegionAWS.md"
          - Kubernetes deployments for cloud platforms:
              - Introduction: "deployK8sCloud.md"
              - Deploy Peered EKS clusters: "deployK8s-AWS.md"
              - Deploy to Azure Kubernetes Service: "deployK8s-AKS.md"
              - Sizing Kubernetes clusters: "k8sClusterSizing.md"
          - Deploy Hashicorp Vault: "deployVault.md"
  - CUSTOMIZING:
      - Introduction: "config.md"
      - Server Profiles:
          - Introduction: "containerAnatomy.md"
          - Structure: "profileStructures.md"
          - Customization: "profiles.md"
          - Build Your Own ...: "buildPingFederateProfile.md"
          - Layering: "profilesLayered.md"
          - Env Substitution: "profilesSubstitution.md"
          - Private Github Repos: "privateRepos.md"
      - Customizing YAML files: "yamlFiles.md"
      - Variables and Scope: "variableScoping.md"
      - Using Certificates: "usingCertificates.md"
      - Using DevOps Hooks: "hooks.md"
      - Using Release Tags: "releaseTags.md"
      - Using Supported Images: "imageSupport.md"
      - Using Hashicorp Vault: "usingVault.md"
      - Securing the Containers: "secureContainers.md"
      - Eval of DevOps Image Security: "dockerImageSecurity.md"
      - Adding a MOTD: "addMOTD.md"
      - Managing Deployments:
          - Introduction: "manage.md"
          - Upgrading PingFederate: "upgradePingfederate.md"
          - Upgrading PingDirectory: "upgradePingDirectory.md"
      - Utilities:
          - ping-devops: "pingDevopsUtil.md"
          - ldap-sdk-tools: "ldapsdkUtil.md"
      - Troubleshooting: "troubleshooting.md"
      - DevOps Images Reference:
          - Introduction: "dockerImagesRef.md"
          - PingFederate: "docker-images/pingfederate/README.md"
          - PingAccess: "docker-images/pingaccess/README.md"
          - PingDirectory: "docker-images/pingdirectory/README.md"
          - PingDirectoryProxy: "docker-images/pingdirectoryproxy/README.md"
          - PingDataGovernance: "docker-images/pingdatagovernance/README.md"
          - PingDataGovernance PAP: "docker-images/pingdatagovernancepap/README.md"
          - PingDataSync: "docker-images/pingdatasync/README.md"
          - PingDelegator: "docker-images/pingdelegator/README.md"
          - PingCentral: "docker-images/pingcentral/README.md"
          - PingIntelligence: "docker-images/pingintelligence/README.md"
          - ldap-sdk-tools: "docker-images/ldap-sdk-tools/README.md"
          - Ping Data Console: "docker-images/pingdataconsole/README.md"
          - PingDownloader: "docker-images/pingdownloader/README.md"
          - PingBase: "docker-images/pingbase/README.md"
          - PingCommon: "docker-images/pingcommon/README.md"
          - PingDataCommon: "docker-images/pingdatacommon/README.md"
          - Apache JMeter: "docker-images/apache-jmeter/README.md"
  - RELEASE NOTES:
      - Current: "relnotes-2010.md"
      - Version 2009: "relnotes-2009.md"
      - Version 2008: "relnotes-2008.md"
      - Version 2007: "relnotes-2007.md"
      - Version 2006: "relnotes-2006.md"
      - Version 2005: "relnotes-2005.md"
      - Version 2004: "relnotes-2004.md"
      - Version 2003: "relnotes-2003.md"

  - LICENSE: LICENSE.md
  - DISCLAIMER: DISCLAIMER.md
  - THIRD-PARTY SOFTWARE: 3RD_PARTY_SOFTWARE.md
  - CONTRIBUTING: CONTRIBUTING.md

