site_name: Ping Identity DevOps
repo_name: pingidentity/pingidentity-devops-getting-started
repo_url: https://github.com/pingidentity/pingidentity-devops-getting-started
site_url: https://devops.pingidentity.com/
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
   # scheme: preference
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

nav:
  - DevOps @ Ping: "README.md"
  - Overview: "overview.md"
  - Get Started:
      - Introduction: "getStarted.md"
      - DevOps Registration: "devopsRegistration.md"
      - Deploy Example Stack: "getStartedWithGitRepo.md"
      - DevOps Product Licenses: "prodLicense.md"
      - Using Your DevOps User and Key: "devopsUserKey.md"
      - Using Existing Product License: "existingLicense.md"
      - Saving Your Configuration Changes: "saveConfigs.md"
  - Working With Images:
      - Introduction: "deploy.md"
      - Build Image Locally: "buildLocal.md"
      # TODO: Requires rework once image docker run commands are linked
      #- Deploy Standalone Containers: "deployStandalone.md"
      - Deploy with Docker-Compose:
          - Introduction: "deployCompose.md"
          - Deploy PingFederate and PingDirectory Stack: "deploySimpleStack.md"
          - Deploy Replicated PingDirectory Pair: "deployReplication.md"
          - Deploy PingDirectory and PingDataSync: "deploySync.md"
          - Deploy PingCentral: "deployPingCentral.md"
          - Deploy PingFederate Cluster: "deployPfCluster.md"
          - Deploy PingAccess Cluster: "deployPaCluster.md"
          - Deploy PingDataGovernance with PAP: "deployPdgPap.md"
          - Deploy Monitoring Stack: "deployMonitoringStack.md"
          - Deploy an Elasticsearch SIEM Stack: "deploySiemStack.md"
      - Deploy with Kubernetes:
          - Introduction: "deployK8s.md"
          - Deploy with PingIdentiy Helm Charts: "deployHelm.md"
          - PingDirectory Deployments Across Kubernetes Clusters: "deployK8sPD-clusters.md"
          - Kubernetes Deployments For General Use:
              - Introduction: "deployK8sGeneral.md"
              - Orchestrate Standalone Deployments: "deployK8sStandalone.md"
              - Orchestrate a Full Stack Deployment: "deployK8sFullstack.md"
              - Orchestrate a Replicated PingDirectory Deployment: "deployK8sReplicated.md"
              - Orchestrate a PingAccess Cluster Deployment: "deployK8sPA-cluster.md"
              - Orchestrate a PingFederate Cluster Deployment: "deployK8sPF-cluster.md"
              - Deploy PingFederate Across Multiple Kubernetes Clusters:
                  - Introduction: "deployK8sPFclusters.md"
                  - PingFederate Across Kubernetes with DNS: "deployPFMultiRegionDNS.md"
                  - PingFederate Across Kubernetes with S3: "deployPFMultiRegionAWS.md"
          - Kubernetes Deployments For Cloud Platforms:
              - Introduction: "deployK8sCloud.md"
              - Deploy Peered EKS Clusters: "deployK8s-AWS.md"
              - Deploy to Azure Kubernetes Service: "deployK8s-AKS.md"
              - Sizing Kubernetes Clusters: "k8sClusterSizing.md"
          - Deploy Hashicorp Vault: "deployVault.md"
  - Customizing:
      - Introduction: "config.md"
      - Server Profiles:
          - Deployment: "containerAnatomy.md"
          - Structure: "profileStructures.md"
          - Customization: "profiles.md"
          - Build Your Own ...: "buildPingFederateProfile.md"
          - Layering: "profilesLayered.md"
          - Env Substitution: "profilesSubstitution.md"
          - Private Github Repos: "privateRepos.md"
      - Customizing YAML files: "yamlFiles.md"
      - Variables and Scope: "variableScoping.md"
      - Using Certificates: "usingCertificates.md"
      - Using DevOps Hooks: "hooks.md"
      - Using Release Tags: "releaseTags.md"
      - Using Supported Images: "imageSupport.md"
      - Using Hashicorp Vault: "usingVault.md"
      - Securing the Containers: "secureContainers.md"
      - Eval of DevOps Image Security: "dockerImageSecurity.md"
      - Adding a MOTD: "addMOTD.md"
      - Managing Deployments:
          - Introduction: "manage.md"
          - Upgrading PingFederate: "upgradePingfederate.md"
          - Upgrading PingDirectory: "upgradePingDirectory.md"
      - Utilities:
          - ping-devops: "pingDevopsUtil.md"
          - ldap-sdk-tools: "ldapsdkUtil.md"
      - Troubleshooting: "troubleshooting.md"
      - DevOps Images Reference:
          - Introduction: "dockerImagesRef.md"
          - PingFederate: "docker-images/pingfederate/README.md"
          - PingAccess: "docker-images/pingaccess/README.md"
          - PingDirectory: "docker-images/pingdirectory/README.md"
          - PingDirectoryProxy: "docker-images/pingdirectoryproxy/README.md"
          - PingDataGovernance: "docker-images/pingdatagovernance/README.md"
          - PingDataGovernance PAP: "docker-images/pingdatagovernancepap/README.md"
          - PingDataSync: "docker-images/pingdatasync/README.md"
          - PingDelegator: "docker-images/pingdelegator/README.md"
          - PingCentral: "docker-images/pingcentral/README.md"
          - PingIntelligence: "docker-images/pingintelligence/README.md"
          - ldap-sdk-tools: "docker-images/ldap-sdk-tools/README.md"
          - Ping Data Console: "docker-images/pingdataconsole/README.md"
          - PingDownloader: "docker-images/pingdownloader/README.md"
          - PingBase: "docker-images/pingbase/README.md"
          - PingCommon: "docker-images/pingcommon/README.md"
          - PingDataCommon: "docker-images/pingdatacommon/README.md"
          - Apache JMeter: "docker-images/apache-jmeter/README.md"
  - Release Notes:
      - Current: "relnotes-2010.md"
      - Version 2009: "relnotes-2009.md"
      - Version 2008: "relnotes-2008.md"
      - Version 2007: "relnotes-2007.md"
      - Version 2006: "relnotes-2006.md"
      - Version 2005: "relnotes-2005.md"
      - Version 2004: "relnotes-2004.md"
      - Version 2003: "relnotes-2003.md"

  - License: license.md
  - Disclaimer: disclaimer.md
  - Third-Party Software: 3rd_party_software.md
  - Contributing: contributing.md

