kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingAccess getting started demo
#-
#- To access PingAccess Console
#- 
#-    https://localhost:9000/
#-    
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

resources:
- pingaccess.yaml
- configmap.yaml